package router

import (
	"Jinshuzhai-Bookstore/handler/state"
	"Jinshuzhai-Bookstore/handler/user/admin"
	"Jinshuzhai-Bookstore/handler/user/common"
	"errors"
	"github.com/spf13/viper"
	swag "github.com/swaggo/gin-swagger"
	"go.uber.org/zap"
	"net/http"
	"time"

	_ "Jinshuzhai-Bookstore/docs" // docs is generated by Swag CLI, you have to import it.
	"Jinshuzhai-Bookstore/router/middleware"

	"github.com/gin-contrib/pprof"
	ginzap "github.com/gin-contrib/zap"
	"github.com/gin-gonic/gin"
	"github.com/swaggo/gin-swagger/swaggerFiles"
)

func InitRouter() {
	gin.SetMode(viper.GetString("mode"))
	g := gin.New()
	Load(
		// Cores
		g,

		// Global Middlewares
		ginzap.Ginzap(zap.L(), time.RFC3339, false),
		ginzap.RecoveryWithZap(zap.L(), true),
		middleware.RequestId(),
	)

	go testPing()

	startListen(g)
}

// testPing tests if the server is listening
// normally by ping the server address.
func testPing() {
	if err := pingServer(); err != nil {
		zap.L().Error("The router has no response, or it might took too long to start up.", zap.Error(err))
	}
	zap.L().Info("The router has been deployed successfully.")
}

// startListen starts listening the
// requests by http or https protocol.
func startListen(g *gin.Engine) {
	cert := viper.GetString("tls.cert")
	key := viper.GetString("tls.key")
	if cert != "" && key != "" {
		go func() {
			zap.L().Info("Start to listening the incoming requests on https address", zap.String("tls.addr", viper.GetString("tls.addr")))
			zap.L().Error(http.ListenAndServeTLS(viper.GetString("tls.addr"), cert, key, g).Error())
		}()
	}
	zap.L().Info("Start to listening the incoming requests on http address", zap.String("addr", viper.GetString("addr")))
	zap.L().Error(http.ListenAndServe(viper.GetString("addr"), g).Error())
}

// pingServer pings the http server
// to make sure the server is working.
func pingServer() error {
	for i := 0; i < viper.GetInt("max_ping_count"); i++ {
		// Ping the server by sending a GET request to `/state/health`.
		resp, err := http.Get(viper.GetString("url") + "/state/health")
		if err == nil && resp.StatusCode == 200 {
			return nil
		}

		// Sleep for a second to continue the next ping.
		zap.L().Info("Waiting for the router, retry in 1 second.")
		time.Sleep(time.Second)
	}
	return errors.New("connect to the router failed")
}

// Load loads the middlewares, routes, handlers.
func Load(g *gin.Engine, mw ...gin.HandlerFunc) *gin.Engine {
	// Local Middlewares.
	g.Use(middleware.NoCache)
	g.Use(middleware.Options)
	g.Use(middleware.Secure)
	g.Use(mw...)
	// 404 Handler.
	g.NoRoute(func(c *gin.Context) {
		c.String(http.StatusNotFound, "The requested resource is not found.")
	})

	// swagger api docs
	g.GET("/swagger/*any", swag.WrapHandler(swaggerFiles.Handler))

	// pprof router
	pprof.Register(g)

	// The health check handlers
	st := g.Group("/state")
	{
		st.GET("/health", state.HealthCheck)
		st.GET("/disk", state.DiskCheck)
		st.GET("/cpu", state.CPUCheck)
		st.GET("/ram", state.RAMCheck)
	}
	// common

	// api version group
	v := g.Group("/v1")
	u := v.Group("/user")
	{
		// user login router
		u.POST("/login", common.Login)
		// user register router
		u.POST("/register", common.Create)
	}

	// common user router group
	c := u.Group("/common")
	// use authentication middleware
	c.Use(middleware.AuthMiddleware())
	{
		// common user router
		c.PUT("", common.SelfUpd)
		c.DELETE("", common.SelfDel)
	}
	// admin user router group
	a := u.Group("/admin")
	// use authentication middleware
	a.Use(middleware.AuthMiddleware())
	// use HasPermission middleware
	a.Use(middleware.HasPermission())
	{
		// admin user router
		a.DELETE("/:id", admin.Delete)
		a.PUT("/:id", admin.Update)
		a.GET("", admin.List)
		a.GET("/:id", admin.Get)
	}

	return g
}
