@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 用户 as general
participant 路由模块 as router
participant 创建订单函数 as order
participant 获取购物车函数 as cart
participant 清空购物车函数 as cc
participant 数据库 as database
participant 日志模块 as log

general -> router++ : 创建订单请求

router -> order++ : 创建订单函数调用请求
order -> log: 日志记录请求

order -> cart ++: 获取购物车函数调用请求
cart -> database ++: 获取购物车请求
database -> cart --: 获取购物车响应
cart ->order --: 获取购物车函数调用响应
order -> database ++: 创建订单请求
database --> order --: 创建订单响应
order -> cc ++: 清空购物车函数调用请求
cc -> database ++: 清空购物车请求
database -> cc --: 清空购物车响应
cc --> order --: 清空购物车函数调用响应
order --> router --:创建订单函数调用响应


router --> general-- : 创建订单响应
@enduml