// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://github.com/zouyonghe",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/zouyonghe",
            "email": "1259085392z@gmail.com"
        },
        "license": {
            "name": "GPLv3",
            "url": "https://www.gnu.org/licenses/gpl-3.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/book": {
            "get": {
                "description": "List books by fuzzy title and exact category with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "List books",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fuzzy book title",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "exact book category",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page number, default 1",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size, default 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/book.SwaggerListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Add a new book (seller or admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Add a new book",
                "parameters": [
                    {
                        "description": "book information",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/book.AddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/book.SwaggerAddResponse"
                        }
                    }
                }
            }
        },
        "/book/{id}": {
            "get": {
                "description": "Get a book specified by book ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Get a book",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "the ID of the book",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/book.SwaggerGetResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update a book specified by book ID (seller or admin only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Update a book",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "the ID of the book",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "book information",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/book.AddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/book.SwaggerUpdateResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a book specified by book ID (seller or admin only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book"
                ],
                "summary": "Delete a book",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "the ID of the book",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/book.SwaggerDeleteResponse"
                        }
                    }
                }
            }
        },
        "/cart": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Show the books and total price of the current user's cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Show the cart",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cart.SwaggerShowCartResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Add a book to the current user's cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Add a book to the cart",
                "parameters": [
                    {
                        "description": "book ID and number",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cart.AddCartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cart.SwaggerAddCartResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove the specified number of a book from the current user's cart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Remove books from the cart",
                "parameters": [
                    {
                        "description": "book ID and number",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cart.DeleteCartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cart.SwaggerDeleteCartResponse"
                        }
                    }
                }
            }
        },
        "/cart/all": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove all books from the current user's cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cart"
                ],
                "summary": "Clear the cart",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cart.SwaggerClearCartResponse"
                        }
                    }
                }
            }
        },
        "/order": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List orders: general users see their own orders, sellers and admins see all accepted orders",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "List orders",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "page number, default 1",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size, default 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/order.SwaggerListResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Deal with an order: operation=accept pays the order, operation=cancel cancels the order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Deal with an order",
                "parameters": [
                    {
                        "description": "order ID and operation",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.DealOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/order.SwaggerDealOrderResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Create an order from all books in the current user's cart and clear the cart",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Create an order",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/order.SwaggerCreateOrderResponse"
                        }
                    }
                }
            }
        },
        "/state/cpu": {
            "get": {
                "description": "Check the cpu load of the server",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "state"
                ],
                "summary": "CPU check",
                "responses": {
                    "200": {
                        "description": "OK - Load average: ...",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/state/disk": {
            "get": {
                "description": "Check the disk usage of the server",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "state"
                ],
                "summary": "Disk check",
                "responses": {
                    "200": {
                        "description": "OK - Free space: ...",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/state/health": {
            "get": {
                "description": "Show OK as the ping-pong result",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "state"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/state/ram": {
            "get": {
                "description": "Check the ram usage of the server",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "state"
                ],
                "summary": "RAM check",
                "responses": {
                    "200": {
                        "description": "OK - Free space: ...",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/admin": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "List users account by specified username format include id, username, role, etc. The password hash is never returned.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/admin"
                ],
                "summary": "List users account by specified username format.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "fuzzy username",
                        "name": "username",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page number, default 1",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size, default 10",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"totalCount\":1,\"userList\":[{\"id\":1,\"username\":\"admin\",\"ShortId\":\"5P9Ia4QnR\",\"role\":\"admin\",\"createdAt\":\"2021-04-18 15:40:33\",\"updatedAt\":\"2021-04-18 15:40:33\"}]}}",
                        "schema": {
                            "$ref": "#/definitions/user.SwaggerListResponse"
                        }
                    }
                }
            }
        },
        "/user/admin/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get a user account specified by user ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/admin"
                ],
                "summary": "Get a user information",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "the ID of the specified user to update",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"UserID\":5,\"username\":\"傅秀英\",\"role\":\"general\"}}",
                        "schema": {
                            "$ref": "#/definitions/user.SwaggerGetResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update a user account specified by user ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/admin"
                ],
                "summary": "Update a user account",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "the ID of the specified user to update",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "user information include username and password",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"UserID\":5}}",
                        "schema": {
                            "$ref": "#/definitions/user.SwaggerUpdateResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Delete a user by user ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/admin"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "the ID of the specified user to delete",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"UserID\":5}}",
                        "schema": {
                            "$ref": "#/definitions/user.SwaggerDeleteResponse"
                        }
                    }
                }
            }
        },
        "/user/common": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get the information of the user specified by the token. The password hash is never returned.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/common"
                ],
                "summary": "Get self user information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.SwaggerGetResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Update the current user information by username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/common"
                ],
                "summary": "Update the current user information",
                "parameters": [
                    {
                        "description": "Create a new user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.SelfUpdRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"UserID\":6,\"username\":\"夏秀兰\"}}",
                        "schema": {
                            "$ref": "#/definitions/user.SwaggerSelfUpdResponse"
                        }
                    }
                }
            }
        },
        "/user/common/": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "SelfDel deletes the user of token specified",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/common"
                ],
                "summary": "SelfDel deletes the user of token specified",
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"UserID\":8}}",
                        "schema": {
                            "$ref": "#/definitions/user.SwaggerSelfDelResponse"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Login a user account with username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Login  a user account",
                "parameters": [
                    {
                        "description": "Login account",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"UserID\":7,\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA0NTkzODEsImlkIjo3LCJuYmYiOjE2NTA0NTkzODEsInJvbGUiOiJnZW5lcmFsIiwidXNlcm5hbWUiOiLkuIHno4oifQ.0kA4whaE9bZjXu4bN3Sw0DgrKwYzJ7kZenaGDOcdFRQ\"}}",
                        "schema": {
                            "$ref": "#/definitions/user.SwaggerLoginResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Register a new user by username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "user information include username and password",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"OK\",\"data\":{\"UserID\":12,\"username\":\"汤桂英\",\"role\":\"business\"}}",
                        "schema": {
                            "$ref": "#/definitions/user.SwaggerRegisterResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "book.AddRequest": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "isSell": {
                    "type": "boolean"
                },
                "number": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "publishDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "book.AddResponse": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "book.DeleteResponse": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "book.ListResponse": {
            "type": "object",
            "properties": {
                "bookList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BookInfo"
                    }
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "book.SwaggerAddResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/book.AddResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "book.SwaggerDeleteResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/book.DeleteResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "book.SwaggerGetResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/model.Book"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "book.SwaggerListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/book.ListResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "book.SwaggerUpdateResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/book.UpdateResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "book.UpdateResponse": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "cart.AddCartRequest": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "number": {
                    "type": "integer"
                }
            }
        },
        "cart.AddCartResponse": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "Number": {
                    "type": "integer"
                }
            }
        },
        "cart.ClearCartResponse": {
            "type": "object",
            "properties": {
                "Message": {
                    "type": "string"
                }
            }
        },
        "cart.DeleteCartRequest": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "Number": {
                    "type": "integer"
                }
            }
        },
        "cart.DeleteCartResponse": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "Number": {
                    "type": "integer"
                }
            }
        },
        "cart.ShowCartResponse": {
            "type": "object",
            "properties": {
                "booksInfo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BookBase"
                    }
                },
                "cartPrice": {
                    "type": "number"
                }
            }
        },
        "cart.SwaggerAddCartResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/cart.AddCartResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "cart.SwaggerClearCartResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/cart.ClearCartResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "cart.SwaggerDeleteCartResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/cart.DeleteCartResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "cart.SwaggerShowCartResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/cart.ShowCartResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Book": {
            "type": "object",
            "required": [
                "author",
                "category",
                "number",
                "price",
                "publishDate",
                "title"
            ],
            "properties": {
                "author": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 1
                },
                "category": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 1
                },
                "isSell": {
                    "type": "boolean"
                },
                "number": {
                    "type": "integer",
                    "minimum": 0
                },
                "price": {
                    "type": "number",
                    "minimum": 0
                },
                "publishDate": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 1
                }
            }
        },
        "model.BookBase": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "index": {
                    "type": "integer"
                },
                "number": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.BookInfo": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "author": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "isSell": {
                    "type": "boolean"
                },
                "number": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "publishDate": {
                    "type": "string"
                },
                "shortId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.OrderBook": {
            "type": "object",
            "properties": {
                "BookID": {
                    "type": "integer"
                },
                "Number": {
                    "type": "integer"
                },
                "unitPrice": {
                    "type": "number"
                }
            }
        },
        "model.OrderInfo": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "orderBook": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OrderBook"
                    }
                },
                "orderPrice": {
                    "type": "number"
                },
                "order_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.UserInfo": {
            "type": "object",
            "properties": {
                "ShortId": {
                    "type": "string"
                },
                "UserID": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "order.CreateOrderResponse": {
            "type": "object",
            "properties": {
                "orderId": {
                    "type": "integer"
                }
            }
        },
        "order.DealOrderRequest": {
            "type": "object",
            "properties": {
                "operation": {
                    "type": "string"
                },
                "orderId": {
                    "type": "integer"
                }
            }
        },
        "order.DealOrderResponse": {
            "type": "object",
            "properties": {
                "orderId": {
                    "type": "integer"
                }
            }
        },
        "order.ListResponse": {
            "type": "object",
            "properties": {
                "orderList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OrderInfo"
                    }
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "order.SwaggerCreateOrderResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/order.CreateOrderResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "order.SwaggerDealOrderResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/order.DealOrderResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "order.SwaggerListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/order.ListResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.DeleteResponse": {
            "type": "object",
            "properties": {
                "UserID": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.GetResponse": {
            "type": "object",
            "properties": {
                "UserID": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "user.RegisterRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.RegisterResponse": {
            "type": "object",
            "properties": {
                "UserID": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.SelfDelResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "userID": {
                    "type": "integer"
                }
            }
        },
        "user.SelfUpdRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.SelfUpdResponse": {
            "type": "object",
            "properties": {
                "UserID": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.SwaggerDeleteResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/user.DeleteResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.SwaggerGetResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/user.GetResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.SwaggerListResponse": {
            "type": "object",
            "properties": {
                "totalCount": {
                    "type": "integer"
                },
                "userList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UserInfo"
                    }
                }
            }
        },
        "user.SwaggerLoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/user.LoginResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.SwaggerRegisterResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/user.RegisterResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.SwaggerSelfDelResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/user.SelfDelResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.SwaggerSelfUpdResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/user.SelfUpdResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.SwaggerUpdateResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/user.UpdateResponse"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "user.UpdateRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.UpdateResponse": {
            "type": "object",
            "properties": {
                "UserID": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.7.0",
	Host:             "127.0.0.1:8081",
	BasePath:         "/v1",
	Schemes:          []string{"http", "https"},
	Title:            "High-Performance-Online-Bookstore",
	Description:      "The jinshuzhai bookstore api server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
