basePath: /v1
definitions:
  model.UserInfo:
    properties:
      ShortId:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      password:
        type: string
      role:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  user.CreateRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  user.CreateResponse:
    properties:
      userId:
        type: integer
      username:
        type: string
    type: object
  user.DeleteResponse:
    properties:
      userId:
        type: integer
    type: object
  user.GetResponse:
    properties:
      password:
        type: string
      role:
        type: string
      userId:
        type: integer
      username:
        type: string
    type: object
  user.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  user.LoginResponse:
    properties:
      token:
        type: string
      userId:
        type: integer
    type: object
  user.SelfDelResponse:
    properties:
      userId:
        type: integer
    type: object
  user.SelfUpdRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  user.SelfUpdResponse:
    properties:
      userId:
        type: integer
      username:
        type: string
    type: object
  user.SwaggerCreateResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/user.CreateResponse'
      message:
        type: string
    type: object
  user.SwaggerDeleteResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/user.DeleteResponse'
      message:
        type: string
    type: object
  user.SwaggerGetResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/user.GetResponse'
      message:
        type: string
    type: object
  user.SwaggerListResponse:
    properties:
      totalCount:
        type: integer
      userList:
        items:
          $ref: '#/definitions/model.UserInfo'
        type: array
    type: object
  user.SwaggerLoginResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/user.LoginResponse'
      message:
        type: string
    type: object
  user.SwaggerSelfDelResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/user.SelfDelResponse'
      message:
        type: string
    type: object
  user.SwaggerSelfUpdResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/user.SelfUpdResponse'
      message:
        type: string
    type: object
  user.SwaggerUpdateResponse:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/user.UpdateResponse'
      message:
        type: string
    type: object
  user.UpdateRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  user.UpdateResponse:
    properties:
      userId:
        type: integer
      username:
        type: string
    type: object
host: 127.0.0.1:8081
info:
  contact:
    email: 1259085392z@gmail.com
    name: API Support
    url: https://github.com/zouyonghe
  description: The jinshuzhai bookstore api server.
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.html
  termsOfService: https://github.com/zouyonghe
  title: Jinshuzhai-Bookstore
  version: "0.3"
paths:
  /user/admin:
    get:
      description: List all users account include id, username, encrypted password,
        etc
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"totalCount":1,"userList":[{"id":1,"username":"admin","ShortId":"5P9Ia4QnR","password":"$2a$10$Fv9BWzqsiQ.JuuGdcXdvN.Fx3ml.dVR47W22GoJMWQAlm9wHQIMVe","role":"admin","createdAt":"2021-04-18
            15:40:33","updatedAt":"2021-04-18 15:40:33"}]}}'
          schema:
            $ref: '#/definitions/user.SwaggerListResponse'
      security:
      - ApiKeyAuth: []
      summary: List all users account
      tags:
      - user/admin
  /user/admin/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user by user ID
      parameters:
      - description: the ID of the specified user to delete
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"userId":5}}'
          schema:
            $ref: '#/definitions/user.SwaggerDeleteResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete a user
      tags:
      - user/admin
    get:
      description: Get a user account specified by user ID
      parameters:
      - description: the ID of the specified user to update
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"username":"傅秀英","password":"$2a$10$5pLrLpEQ1HAD2Hcm3Bnud.Shhmf5bTaf1yTWYloot0i5nvn1Td4hq","role":"general"}}'
          schema:
            $ref: '#/definitions/user.SwaggerGetResponse'
      security:
      - ApiKeyAuth: []
      summary: Get a user information
      tags:
      - user/admin
    put:
      consumes:
      - application/json
      description: Update a user account specified by user ID
      parameters:
      - description: the ID of the specified user to update
        in: path
        name: id
        required: true
        type: integer
      - description: user information include username and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"userId":5}}'
          schema:
            $ref: '#/definitions/user.SwaggerUpdateResponse'
      security:
      - ApiKeyAuth: []
      summary: Update a user account
      tags:
      - user/admin
  /user/common:
    put:
      consumes:
      - application/json
      description: Update the current user information by username and password
      parameters:
      - description: Create a new user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.SelfUpdRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"userId":6,"username":"夏秀兰"}}'
          schema:
            $ref: '#/definitions/user.SwaggerSelfUpdResponse'
      security:
      - ApiKeyAuth: []
      summary: Update the current user information
      tags:
      - user/common
  /user/common/:
    delete:
      description: SelfDel deletes the user of token specified
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"userId":8}}'
          schema:
            $ref: '#/definitions/user.SwaggerSelfDelResponse'
      security:
      - ApiKeyAuth: []
      summary: SelfDel deletes the user of token specified
      tags:
      - user/common
  /user/login:
    post:
      consumes:
      - application/json
      description: Login a user account with username and password
      parameters:
      - description: Login account
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"userId":7,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTA0NTkzODEsImlkIjo3LCJuYmYiOjE2NTA0NTkzODEsInJvbGUiOiJnZW5lcmFsIiwidXNlcm5hbWUiOiLkuIHno4oifQ.0kA4whaE9bZjXu4bN3Sw0DgrKwYzJ7kZenaGDOcdFRQ"}}'
          schema:
            $ref: '#/definitions/user.SwaggerLoginResponse'
      summary: Login  a user account
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: Create a new user by username and password
      parameters:
      - description: user information include username and password
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":0,"message":"OK","data":{"userId":"7","username":"顾磊"}}'
          schema:
            $ref: '#/definitions/user.SwaggerCreateResponse'
      summary: Create a new user
      tags:
      - user
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
